//**************************************************************************************************
//                         Copyright (C) 2009 RCZI
//--------------------------------------------------------------------------------------------------
// FILENAME....... scsi.h
//--------------------------------------------------------------------------------------------------
//                           SCSI Command
//-------------------------------------------------------------------------------------------------
// !: arch: tms320c64xx
// !: sarc: all
//
// !: codepage: cp1251 
//
// !: d: Описание кодов "SCSI Sense Key", прототипов и структур.
// !: -:
//***sss********************************************************************************************
#ifndef		__SCSI_Command_H__
#define   __SCSI_Command_H__
#include    <os_types.h>
//--- Sense key and sense code definitions -----------------------------------
// see SPC3 R23 4.5.6 Sense key and sense code definitions (page 41):
#define SCSI_SENSE_KEY_NO_SENSE                  0x0 
#define SCSI_SENSE_KEY_RECOVERED_ERROR           0x1
#define SCSI_SENSE_KEY_NOT_READY                 0x2
#define SCSI_SENSE_KEY_MEDIUM_ERROR              0x3
#define SCSI_SENSE_KEY_HARDWARE_ERROR            0x4
#define SCSI_SENSE_KEY_ILLEGAL_REQUEST           0x5
#define SCSI_SENSE_KEY_UNIT_ATTENTION            0x6
#define SCSI_SENSE_KEY_DATA_PROTECT              0x7
#define SCSI_SENSE_KEY_BLANK_CHECK               0x8
#define SCSI_SENSE_KEY_VENDOR_SPECIFIC           0x9
#define SCSI_SENSE_KEY_COPY_ABORTED              0xA
#define SCSI_SENSE_KEY_ABORTED_COMMAND           0xB
#define SCSI_SENSE_KEY_OBSOLETE                  0xC
#define SCSI_SENSE_KEY_VOLUME_OVERFLOW           0xD
#define SCSI_SENSE_KEY_MISCOMPARE                0xE
#define SCSI_SENSE_KEY_RESERVED                  0xF

//--- Additional Sense codes and Additional Sense codes qualifier ------------
//ASC   [15-08]
//ASCQ  [07-00]
// part 1
#define ACCESS_DENIED_ACL_LUN_CONFLICT                                 0x200B
#define ACCESS_DENIED_ENROLLMENT_CONFLICT                              0x2008
#define ACCESS_DENIED_INITIATOR_PENDING-ENROLLED                       0x2001
#define ACCESS_DENIED_INVALID_LU_IDENTIFIER                            0x2009
#define ACCESS_DENIED_INVALID_MGMT_ID_KEY                              0x2003
#define ACCESS_DENIED_INVALID_PROXY_TOKEN                              0x200A
#define ACCESS_DENIED_NO_ACCESS_RIGHTS                                 0x2002
#define ACK_NAK_TIMEOUT                                                0x4B03
#define ADD_LOGICAL_UNIT_FAILED                                        0x6702
#define ADDRESS_MARK_NOT_FOUND_FOR_DATA_FIELD                          0x1300
#define ADDRESS_MARK_NOT_FOUND_FOR_ID_FIELD                            0x1200
#define ASSIGN_FAILURE_OCCURRED                                        0x6708
#define ASSOCIATED_WRITE_PROTECT                                       0x2703
#define ASYMMETRIC_ACCESS_STATE_CHANGED                                0x2A06
#define ASYNCHRONOUS_INFORMATION_PROTECTION_ERROR_DETECTED             0x4704
#define ATTACHMENT_OF_LOGICAL_UNIT_FAILED                              0x6706
#define AUDIO_PLAY_OPERATION_IN_PROGRESS                               0x0011
#define AUDIO_PLAY_OPERATION_PAUSED                                    0x0012
#define AUDIO_PLAY_OPERATION_STOPPED_DUE_TO_ERROR                      0x0014
#define AUDIO_PLAY_OPERATION_SUCCESSFULLY_COMPLETED                    0x0013
#define AUTOMATIC_DOCUMENT_FEEDER_COVER_UP                             0x6600
#define AUTOMATIC_DOCUMENT_FEEDER_LIFT_UP                              0x6601
#define AUXILIARY_MEMORY_OUT_OF_SPACE                                  0x5506
// part 2                                                               
#define AUXILIARY_MEMORY_READ_ERROR                                    0x1112
#define AUXILIARY_MEMORY_WRITE_ERROR                                   0x0C0B
#define BEGINNING_OF_PARTITION_MEDIUM_DETECTED                         0x0004
#define BLOCK_NOT_COMPRESSIBLE                                         0x0C06
#define BLOCK_SEQUENCE_ERROR                                           0x1404
#define BUS_DEVICE_RESET_FUNCTION_OCCURRED                             0x2903
#define CANNOT_DECOMPRESS_USING_DECLARED_ALGORITHM                     0x110E
#define CANNOT_FORMAT_MEDIUM_INCOMPATIBLE_MEDIUM                       0x3006
#define CANNOT_READ_MEDIUM_INCOMPATIBLE_FORMAT                         0x3002
#define CANNOT_READ_MEDIUM_UNKNOWN_FORMAT                              0x3001
#define CANNOT_WRITE_APPLICATION_CODE_MISMATCH                         0x3008
#define CANNOT_WRITE_MEDIUM_INCOMPATIBLE_FORMAT                        0x3005
#define CANNOT_WRITE_MEDIUM_UNKNOWN_FORMAT                             0x3004
#define CAPACITY_DATA_HAS_CHANGED                                      0x2A09
#define CARTRIDGE_FAULT                                                0x5200
#define CD_CONTROL_ERROR                                               0x7300
#define CDB_DECRYPTION_ERROR                                           0x2401
#define CHANGED_OPERATING_DEFINITION                                   0x3F02
#define CIRC_UNRECOVERED_ERROR                                         0x1106
#define CLEANING_CARTRIDGE_INSTALLED                                   0x3003
#define CLEANING_FAILURE                                               0x3007
#define CLEANING_REQUEST_REJECTED                                      0x300A
#define CLEANING_REQUESTED                                             0x0017
#define COMMAND_PHASE ERROR                                            0x4A00
#define COMMAND_SEQUENCE_ERROR                                         0x2C00
#define COMMAND_TO_LOGICAL_UNIT_FAILED                                 0x6E00
#define COMMANDS_CLEARED_BY_ANOTHER_INITIATOR                          0x2F00
#define COMPONENT_DEVICE_ATTACHED                                      0x3F04
#define COMPRESSION_CHECK_MISCOMPARE_ERROR                             0x0C04
#define CONDITIONAL_WRITE_PROTECT                                      0x2706
#define CONFIGURATION_FAILURE                                          0x6700
#define CONFIGURATION_OF_INCAPABLE_LOGICAL_UNITS_FAILED                0x6701
#define CONTROLLER_IMPENDING_FAILURE_ACCESS_TIMES_TOO_HIGH             0x5D25
#define CONTROLLER_IMPENDING_FAILURE_CHANNEL_PARAMETRICS               0x5D27
#define CONTROLLER_IMPENDING_FAILURE_CONTROLLER_DETECTED               0x5D28
#define CONTROLLER_IMPENDING_FAILURE_DATA_ERROR_RATE_TOO_HIGH          0x5D22
#define CONTROLLER_IMPENDING_FAILURE_DRIVE_CALIBRATION_RETRY_COUNT     0x5D2C
#define CONTROLLER_IMPENDING_FAILURE_DRIVE_ERROR_RATE_TOO_HIGH         0x5D21
// part 3                                                               
#define CONTROLLER_IMPENDING_FAILURE_GENERAL_HARD_DRIVE_FAILURE        0x5D20 
#define CONTROLLER_IMPENDING_FAILURE_SEEK_ERROR_RATE_TOO_HIGH          0x5D23 
#define CONTROLLER_IMPENDING_FAILURE_SEEK_TIME_PERFORMANCE             0x5D2A 
#define CONTROLLER_IMPENDING_FAILURE_SPIN_UP_RETRY_COUNT               0x5D2B 
#define CONTROLLER_IMPENDING_FAILURE_START_UNIT_TIMES_TOO_HIGH         0x5D26 
#define CONTROLLER_IMPENDING_FAILURE_THROUGHPUT_PERFORMANCE            0x5D29 
#define CONTROLLER_IMPENDING_FAILURE_TOO_MANY_BLOCK_REASSIGNS          0x5D24 
#define COPY_CANNOT_EXECUTE_SINCE_HOST_CANNOT_DISCONNECT               0x2B00 
#define COPY_PROTECTION_KEY_EXCHANGE_FAILURE_AUTHENTICATION FAILURE    0x6F00 
#define COPY_PROTECTION_KEY_EXCHANGE_FAILURE_KEY_NOT_ESTABLISHED       0x6F02 
#define COPY_PROTECTION_KEY_EXCHANGE_FAILURE_KEY_NOT_PRESENT           0x6F01 
#define COPY_SEGMENT_GRANULARITY_VIOLATION                             0x260D 
#define COPY_TARGET_DEVICE_DATA_OVERRUN                                0x0D05 
#define COPY_TARGET_DEVICE_DATA_UNDERRUN                               0x0D04 
#define COPY_TARGET_DEVICE_NOT_REACHABLE                               0x0D02 
#define CREATION_OF_LOGICAL_UNIT_FAILED                                0x6707 
#define CURRENT_PROGRAM_AREA_IS_EMPTY                                  0x2C04 
#define CURRENT_PROGRAM_AREA_IS_NOT_EMPTY                              0x2C03 
#define CURRENT_SESSION_NOT_FIXATED_FOR_APPEND                         0x3009 
#define DATA_BLOCK_APPLICATION_TAG_CHECK_FAILED                        0x1002 
#define DATA_BLOCK_GUARD_CHECK_FAILED                                  0x1001 
#define DATA_BLOCK_REFERENCE_TAG_CHECK_FAILED                          0x1003 
#define DATA_CHANNEL_IMPENDING_FAILURE_ACCESS_TIMES_TOO_HIGH           0x5D35 
#define DATA_CHANNEL_IMPENDING_FAILURE_CHANNEL_PARAMETRICS             0x5D37 
#define DATA_CHANNEL_IMPENDING_FAILURE_CONTROLLER_DETECTED             0x5D38 
#define DATA_CHANNEL_IMPENDING_FAILURE_DATA_ERROR_RATE_TOO_HIGH        0x5D32 
#define DATA_CHANNEL_IMPENDING_FAILURE_DRIVE_CALIBRATION_RETRY_COUNT   0x5D3C 
#define DATA_CHANNEL_IMPENDING_FAILURE_DRIVE_ERROR_RATE_TOO_HIGH       0x5D31 
#define DATA_CHANNEL_IMPENDING_FAILURE_GENERAL_HARD_DRIVE_FAILURE      0x5D30 
#define DATA_CHANNEL_IMPENDING_FAILURE_SEEK_ERROR_RATE_TOO_HIGH        0x5D33 
#define DATA_CHANNEL_IMPENDING_FAILURE_SEEK_TIME_PERFORMANCE           0x5D3A 
#define DATA_CHANNEL_IMPENDING_FAILURE_SPIN_UP_RETRY_COUNT             0x5D3B 
#define DATA_CHANNEL_IMPENDING_FAILURE_START_UNIT_TIMES_TOO_HIGH       0x5D36 
#define DATA_CHANNEL_IMPENDING_FAILURE_THROUGHPUT_PERFORMANCE          0x5D39 
#define DATA_CHANNEL_IMPENDING_FAILURE_TOO_MANY_BLOCK_REASSIGNS        0x5D34 
// part 4                                                               
#define DATA_DECRYPTION_ERROR                                          0x2605 
#define DATA_EXPANSION_OCCURRED_DURING_COMPRESSION                     0x0C05 
#define DATA_LOSS_ON_LOGICAL_UNIT                                      0x6900 
#define DATA_OFFSET_ERROR                                              0x4B05 
#define DATA_PATH_FAILURE_SHOULD_USE_40_NN                             0x4100 
#define DATA_PHASE_CRC_ERROR_DETECTED                                  0x4701 
#define DATA_PHASE_ERROR                                               0x4B00 
#define DATA_RE_SYNCHRONIZATION_ERROR                                  0x1107 
#define DATA_SYNC_ERROR_DATA_AUTO_REALLOCATED                          0x1603 
#define DATA_SYNC_ERROR_DATA_REWRITTEN                                 0x1601 
#define DATA_SYNC_ERROR_RECOMMEND_REASSIGNMENT                         0x1604 
#define DATA_SYNC_ERROR_RECOMMEND_REWRITE                              0x1602 
#define DATA_SYNCHRONIZATION_MARK_ERROR                                0x1600 
#define DE_COMPRESSION_CRC_ERROR                                       0x110D 
#define DECOMPRESSION_EXCEPTION_LONG_ALGORITHM_ID                      0x7100 
#define DECOMPRESSION_EXCEPTION_SHORT_ALGORITHM_ID_OF_NN               0x7000 
#define DEFECT_LIST_ERROR                                              0x1900 
#define DEFECT_LIST_ERROR_IN_GROWN_LIST                                0x1903 
#define DEFECT_LIST_ERROR_IN_PRIMARY_LIST                              0x1902 
#define DEFECT_LIST_NOT_AVAILABLE                                      0x1901 
#define DEFECT_LIST_NOT_FOUND                                          0x1C00 
#define DEFECT_LIST_UPDATE_FAILURE                                     0x3201 
#define DEVICE_IDENTIFIER_CHANGED                                      0x3F05 
#define DEVICE_INTERNAL_RESET                                          0x2904 
#define DIAGNOSTIC_FAILURE_ON_COMPONENT_NN_80H_FFH                     0x4000 
#define DOCUMENT_JAM_IN_AUTOMATIC_DOCUMENT_FEEDER                      0x6602 
#define DOCUMENT_MISS_FEED_AUTOMATIC_IN_DOCUMENT_FEEDER                0x6603 
#define DRIVE_REGION_MUST_BE_PERMANENT_REGION_RESET_COUNT_ERROR        0x6F05 
#define ECHO_BUFFER_OVERWRITTEN                                        0x3F0F 
#define EMPTY_OR_PARTIALLY_WRITTEN_RESERVED_TRACK                      0x7204 
#define ENCLOSURE_FAILURE                                              0x3400 
#define ENCLOSURE_SERVICES_CHECKSUM_ERROR                              0x3505 
#define ENCLOSURE_SERVICES_FAILURE                                     0x3500 
#define ENCLOSURE_SERVICES_TRANSFER_FAILURE                            0x3503 
#define ENCLOSURE_SERVICES_TRANSFER_REFUSED                            0x3504 
#define ENCLOSURE_SERVICES_UNAVAILABLE                                 0x3502 
#define END_OF_MEDIUM_REACHED                                          0x3B0F 
#define END_OF_USER_AREA_ENCOUNTERED_ON_THIS_TRACK                     0x6300 
// part 5                                                               
#define END_OF_DATA_DETECTED                                           0x0005 
#define END_OF_DATA_NOT_FOUND                                          0x1403 
#define END_OF_PARTITION_MEDIUM_DETECTED                               0x0002 
#define ERASE_FAILURE                                                  0x5100 
#define ERASE_FAILURE_INCOMPLETE_ERASE_OPERATION_DETECTED              0x5101 
#define ERASE_OPERATION_IN_PROGRESS                                    0x0018 
#define ERROR_DETECTED_BY_THIRD_PARTY_TEMPORARY_INITIATOR              0x0D00 
#define ERROR_LOG_OVERFLOW                                             0x0A00 
#define ERROR_READING_ISRC_NUMBER                                      0x1110 
#define ERROR_READING_UPC_EAN_NUMBER                                   0x110F 
#define ERROR_TOO_LONG_TO_CORRECT                                      0x1102 
#define ESN_DEVICE_BUSY_CLASS_EVENT                                    0x3806 
#define ESN_MEDIA_CLASS_EVENT                                          0x3804 
#define ESN_POWER_MANAGEMENT_CLASS_EVENT                               0x3802 
#define EVENT_STATUS_NOTIFICATION                                      0x3800 
#define EXCESSIVE_WRITE_ERRORS                                         0x0302 
#define EXCHANGE_OF_LOGICAL_UNIT_FAILED                                0x6704 
#define FAILED_TO_SENSE_BOTTOM_OF_FORM                                 0x3B07 
#define FAILED_TO_SENSE_TOP_OF_FORM                                    0x3B06 
#define FAILURE_PREDICTION_THRESHOLD_EXCEEDED                          0x5D00 
#define FAILURE_PREDICTION_THRESHOLD_EXCEEDED_FALSE                    0x5DFF 
#define FILEMARK_DETECTED                                              0x0001 
#define FILEMARK_OR_SETMARK_NOT_FOUND                                  0x1402 
#define FIRMWARE_IMPENDING_FAILURE_ACCESS_TIMES_TOO_HIGH               0x5D65 
#define FIRMWARE_IMPENDING_FAILURE_CHANNEL_PARAMETRICS                 0x5D67 
#define FIRMWARE_IMPENDING_FAILURE_CONTROLLER_DETECTED                 0x5D68 
#define FIRMWARE_IMPENDING_FAILURE_DATA_ERROR_RATE_TOO_HIGH            0x5D62 
#define FIRMWARE_IMPENDING_FAILURE_DRIVE_CALIBRATION_RETRY_COUNT       0x5D6C 
#define FIRMWARE_IMPENDING_FAILURE_DRIVE_ERROR_RATE_TOO_HIGH           0x5D61 
#define FIRMWARE_IMPENDING_FAILURE_GENERAL_HARD_DRIVE_FAILURE          0x5D60 
#define FIRMWARE_IMPENDING_FAILURE_SEEK_ERROR_RATE_TOO_HIGH            0x5D63 
#define FIRMWARE_IMPENDING_FAILURE_SEEK_TIME_PERFORMANCE               0x5D6A 
#define FIRMWARE_IMPENDING_FAILURE_SPIN_UP_RETRY_COUNT                 0x5D6B 
#define FIRMWARE_IMPENDING_FAILURE_START_UNIT_TIMES_TOO_HIGH           0x5D66 
#define FIRMWARE_IMPENDING_FAILURE_THROUGHPUT_PERFORMANCE              0x5D69 
#define FIRMWARE_IMPENDING_FAILURE_TOO_MANY_BLOCK_REASSIGNS            0x5D64 
#define FOCUS_SERVO_FAILURE                                            0x0902 
#define FORMAT_COMMAND_FAILED                                          0x3101 
#define GENERATION_DOES_NOT_EXIST                                      0x5800 
// part 6                                                               
#define GROWN_DEFECT_LIST_NOT_FOUND                                    0x1C02
#define HARDWARE_IMPENDING_FAILURE_ACCESS_TIMES_TOO_HIGH               0x5D15
#define HARDWARE_IMPENDING_FAILURE_CHANNEL_PARAMETRICS                 0x5D17
#define HARDWARE_IMPENDING_FAILURE_CONTROLLER_DETECTED                 0x5D18
#define HARDWARE_IMPENDING_FAILURE_DATA_ERROR_RATE_TOO_HIGH            0x5D12
#define HARDWARE_IMPENDING_FAILURE_DRIVE_CALIBRATION_RETRY_COUNT       0x5D1C
#define HARDWARE_IMPENDING_FAILURE_DRIVE_ERROR_RATE_TOO_HIGH           0x5D11
#define HARDWARE_IMPENDING_FAILURE_GENERAL_HARD_DRIVE_FAILURE          0x5D10
#define HARDWARE_IMPENDING_FAILURE_SEEK_ERROR_RATE_TOO_HIGH            0x5D13
#define HARDWARE_IMPENDING_FAILURE_SEEK_TIME_PERFORMANCE               0x5D1A
#define HARDWARE_IMPENDING_FAILURE_SPIN_UP_RETRY_COUNT                 0x5D1B
#define HARDWARE_IMPENDING_FAILURE_START_UNIT_TIMES_TOO_HIGH           0x5D16
#define HARDWARE_IMPENDING_FAILURE_THROUGHPUT_PERFORMANCE              0x5D19
#define HARDWARE_IMPENDING_FAILURE_TOO_MANY_BLOCK_REASSIGNS            0x5D14
#define HARDWARE_WRITE_PROTECTED                                       0x2701
#define HEAD_SELECT_FAULT                                              0x0904
#define IO_PROCESS_TERMINATED                                          0x0006
#define ID_CRC_OR_ECC_ERROR                                            0x1000
#define IDLE_CONDITION_ACTIVATED_BY_COMMAND                            0x5E03
#define IDLE_CONDITION_ACTIVATED_BY_TIMER                              0x5E01
#define ILLEGAL_COMMAND_WHILE_IN_EXPLICIT_ADDRESS_MODE                 0x2006
#define ILLEGAL_COMMAND_WHILE_IN_IMPLICIT_ADDRESS_MODE                 0x2007
#define ILLEGAL_COMMAND_WHILE_IN_WRITE_CAPABLE_STATE                   0x2004
#define ILLEGAL_FUNCTION_USE_20_00_24_00_OR_26_00                      0x2200
#define ILLEGAL_MODE_FOR_THIS_TRACK                                    0x6400
#define ILLEGAL_POWER_CONDITION_REQUEST                                0x2C05
#define IMPLICIT_ASYMMETRIC_ACCESS_STATE_TRANSITION_FAILED             0x2A07
#define IMPORT_OR_EXPORT_ELEMENT_ACCESSED                              0x2801
#define INCOMPATIBLE_MEDIUM_INSTALLED                                  0x3000
#define INCOMPLETE_BLOCK_READ                                          0x1108
#define INCORRECT_COPY_TARGET_DEVICE_TYPE                              0x0D03
#define INFORMATION_UNIT_TOO_LONG                                      0x0E02
#define INFORMATION_UNIT_TOO_SHORT                                     0x0E01
#define INFORMATION_UNIT_IU_CRC_ERROR_DETECTED                         0x4703
#define INFORMATIONAL_REFER_TO_LOG                                     0x6A00
#define INITIATOR_DETECTED_ERROR_MESSAGE_RECEIVED                      0x4800
#define INITIATOR_RESPONSE_TIMEOUT                                     0x4B06
#define INLINE_DATA_LENGTH_EXCEEDED                                    0x260B
// part 7                                                               
#define INQUIRY_DATA_HAS_CHANGED                                       0x3F03
#define INSUFFICIENT_ACCESS_CONTROL_RESOURCES                          0x5505
#define INSUFFICIENT_REGISTRATION_RESOURCES                            0x5504
#define INSUFFICIENT_RESERVATION_RESOURCES                             0x5502
#define INSUFFICIENT_RESOURCES                                         0x5503
#define INSUFFICIENT_TIME_FOR_OPERATION                                0x2E00
#define INTERNAL_TARGET_FAILURE                                        0x4400
#define INVALID_ADDRESS_FOR_WRITE                                      0x2102
#define INVALID_BITS_IN_IDENTIFY_MESSAGE                               0x3D00
#define INVALID_COMBINATION_OF_WINDOWS_SPECIFIED                       0x2C02
#define INVALID_COMMAND_OPERATION_CODE                                 0x2000
#define INVALID_DATA_OUT_BUFFER_INTEGRITY_CHECK_VALUE                  0x260F
#define INVALID_ELEMENT_ADDRESS                                        0x2101
#define INVALID_FIELD_IN_CDB                                           0x2400
#define INVALID_FIELD_IN_COMMAND_INFORMATION_UNIT                      0x0E03
#define INVALID_FIELD_IN_PARAMETER_LIST                                0x2600
#define INVALID_INFORMATION_UNIT                                       0x0E00
#define INVALID_MESSAGE_ERROR                                          0x4900
#define INVALID_OPERATION_FOR_COPY_SOURCE_OR_DESTINATION               0x260C
#define INVALID_PACKET_SIZE                                            0x6401
#define INVALID PARAMETER_WHILE_PORT_IS_ENABLED                        0x260E
#define INVALID_RELEASE_OF_PERSISTENT_RESERVATIONи                     0x2604
#define INVALID_TARGET_PORT_TRANSFER_TAG_RECEIVED                      0x4B01
#define NEXUS_LOSS_OCCURRED                                            0x2907
#define L_EC_UNCORRECTABLE_ERROR                                       0x1105
#define LAMP_FAILURE                                                   0x6000
#define LOCATE_OPERATION_FAILURE                                       0x1407
#define LOCATE_OPERATION_IN_PROGRESS                                   0x0019
#define LOG_COUNTER_AT_MAXIMUM                                         0x5B02
#define LOG_EXCEPTION                                                  0x5B00
#define LOG_LIST_CODES_EXHAUSTED                                       0x5B03
#define LOG_PARAMETERS_CHANGED                                         0x2A02
#define LOGICAL_BLOCK_ADDRESS_OUT_OF_RANGE                             0x2100
#define LOGICAL_UNIT_COMMUNICATION_CRC_ERROR_ULTRA_DMA_32              0x0803
#define LOGICAL_UNIT_COMMUNICATION_FAILURE                             0x0800
#define LOGICAL_UNIT_COMMUNICATION_PARITY_ERROR                        0x0802
#define LOGICAL_UNIT_COMMUNICATION_TIME_OUT                            0x0801
#define LOGICAL_UNIT_DOES_NOT_RESPOND_TO_SELECTION                     0x0500
#define LOGICAL_UNIT_FAILED_SELF_CONFIGURATION                         0x4C00
// part 8                                                               
#define LOGICAL_UNIT_FAILED_SELF_TEST                                  0x3E03
#define LOGICAL_UNIT_FAILURE                                           0x3E01
#define LOGICAL_UNIT_FAILURE_PREDICTION_THRESHOLD_EXCEEDED             0x5D02
#define LOGICAL_UNIT_HAS_NOT_SELF_CONFIGURED_YET                       0x3E00
#define LOGICAL_UNIT_IS_IN_PROCESS_OF_BECOMING_READY                   0x0401
#define LOGICAL_UNIT_NOT_ACCESSIBLE_ASYMMETRIC_ACCESS_STATE_TRANSITION 0x040A
#define LOGICAL_UNIT_NOT_ACCESSIBLE_TARGET_PORT_IN_STANDBY_STATE       0x040B
#define LOGICAL_UNIT_NOT_ACCESSIBLE_TARGET_PORT_IN_UNAVAILABLE_STATE   0x040C
#define LOGICAL_UNIT_NOT_CONFIGURED                                    0x6800
#define LOGICAL_UNIT_NOT_READY_AUXILIARY_MEMORY_NOT_ACCESSIBLE         0x0410
#define LOGICAL_UNIT_NOT_READY_CAUSE_NOT_REPORTABLE                    0x0400
#define LOGICAL_UNIT_NOT_READY_FORMAT_IN_PROGRESS                      0x0404
#define LOGICAL_UNIT_NOT_READY_INITIALIZING_COMMAND_REQUIRED           0x0402
#define LOGICAL_UNIT_NOT_READY_LONG_WRITE_IN_PROGRESS                  0x0408
#define LOGICAL_UNIT_NOT_READY_MANUAL_INTERVENTION_REQUIRED            0x0403
#define LOGICAL_UNIT_NOT_READY_NOTIFY_ENABLE_SPINUP_REQUIRED           0x0411
#define LOGICAL_UNIT_NOT_READY_OFFLINE                                 0x0412
#define LOGICAL_UNIT_NOT_READY_OPERATION_IN_PROGRESS                   0x0407
#define LOGICAL_UNIT_NOT_READY_REBUILD_IN_PROGRESS                     0x0405
#define LOGICAL_UNIT_NOT_READY_RECALCULATION_IN_PROGRESS               0x0406
#define LOGICAL_UNIT_NOT_READY_SELF_TEST_IN_PROGRESS                   0x0409
#define LOGICAL_UNIT_NOT_SUPPORTED                                     0x2500
#define LOGICAL_UNIT_SOFTWARE_WRITE_PROTECTED                          0x2702
#define LOGICAL_UNIT_UNABLE_TO_UPDATE_SELF_TEST_LOG                    0x3E04
#define LOW_POWER_CONDITION_ON                                         0x5E00
#define MECHANICAL_POSITIONING_ERROR                                   0x1501
#define MECHANICAL_POSITIONING_OR_CHANGER_ERROR                        0x3B16
#define MEDIA_FAILURE_PREDICTION_THRESHOLD_EXCEEDED                    0x5D01
#define MEDIA_LOAD_OR_EJECT_FAILED                                     0x5300
#define MEDIA_REGION_CODE_IS_MISMATCHED_TO_LOGICAL_UNIT_REGION         0x6F04
#define MEDIUM_AUXILIARY_MEMORY_ACCESSIBLE                             0x3F11
#define MEDIUM_DESTINATION_ELEMENT_FULL                                0x3B0D
#define MEDIUM_FORMAT_CORRUPTED                                        0x3100
#define MEDIUM_LOADABLE                                                0x3F10
#define MEDIUM_MAGAZINE_INSERTED                                       0x3B13
#define MEDIUM_MAGAZINE_LOCKED                                         0x3B14
#define MEDIUM_MAGAZINE_NOT_ACCESSIBLE                                 0x3B11
// part 9                                                                     
#define MEDIUM_MAGAZINE_REMOVED                                        0x3B12
#define MEDIUM_MAGAZINE_UNLOCKED                                       0x3B15
#define MEDIUM_NOT_FORMATTED                                           0x3010
#define MEDIUM_NOT_PRESENT                                             0x3A00
#define MEDIUM_NOT_PRESENT_LOADABLE                                    0x3A03
#define MEDIUM_NOT_PRESENT_MEDIUM_AUXILIARY_MEMORY_ACCESSIBLE          0x3A04
#define MEDIUM_NOT_PRESENT_TRAY_CLOSED                                 0x3A01
#define MEDIUM_NOT_PRESENT_TRAY_OPEN                                   0x3A02
#define MEDIUM_REMOVAL_PREVENTED                                       0x5302
#define MEDIUM_SOURCE_ELEMENT_EMPTY                                    0x3B0E
#define MESSAGE_ERROR                                                  0x4300
#define MICROCODE_HAS_BEEN_CHANGED                                     0x3F01
#define MISCOMPARE_DURING_VERIFY_OPERATION                             0x1D00
#define MISCORRECTED_ERROR                                             0x110A
#define MODE_PARAMETERS_CHANGED                                        0x2A01
#define MODIFICATION_OF_LOGICAL_UNIT_FAILED                            0x6703
#define MULTIPLE_LOGICAL_UNIT_FAILURES                                 0x6901
#define MULTIPLE_PERIPHERAL_DEVICES_SELECTED                           0x0700
#define MULTIPLE_READ_ERRORS                                           0x1103
#define MULTIPLY_ASSIGNED_LOGICAL_UNIT                                 0x6709
#define NAK_RECEIVED                                                   0x4B04
#define ADDITIONAL_SENSE_INFORMATION                                   0x0000
#define NO_CURRENT_AUDIO_STATUS_TO_RETURN                              0x0015
#define NO_DEFECT_SPARE_LOCATION_AVAILABLE                             0x3200
#define NO_GAP_FOUND                                                   0x1109
#define NO_INDEX_SECTOR_SIGNAL                                         0x0100
#define NO_MORE_TRACK_RESERVATIONS_ALLOWED                             0x7205
#define NO_REFERENCE_POSITION_FOUND                                    0x0600
#define NO_SEEK_COMPLETE                                               0x0200
#define NO_WRITE_CURRENT                                               0x0301
#define NONCE_NOT_UNIQUE                                               0x2406
#define NONCE_TIMESTAMP_OUT_OF_RANGE                                   0x2407
#define NOT_READY_TO_READY_CHANGE_MEDIUM_MAY_HAVE_CHANGED              0x2800
#define NOT_RESERVED                                                   0x2C0B
#define OPERATION_IN_PROGRESS                                          0x0016
#define OPERATOR_MEDIUM_REMOVAL_REQUEST                                0x5A01
#define OPERATOR_REQUEST_OR_STATE_CHANGE_INPUT                         0x5A00
#define OPERATOR_SELECTED_WRITE_PERMIT                                 0x5A03
#define OPERATOR_SELECTED_WRITE_PROTECT                                0x5A02                                    
// part 10
#define OUT_OF_FOCUS                                                   0x6102
#define OVERLAPPED_COMMANDS_ATTEMPTED                                  0x4E00
#define OVERWRITE_ERROR_ON_UPDATE_IN_PLACE                             0x2D00
#define OBSOLETE_1                                                     0x2005
#define OBSOLETE_2                                                     0x2402
#define OBSOLETE_3                                                     0x2403
#define PACKET_DOES_NOT_FIT_IN_AVAILABLE_SPACE                         0x6301
#define PAPER_JAM                                                      0x3B05
#define PARAMETER_LIST_LENGTH_ERROR                                    0x1A00
#define PARAMETER_NOT_SUPPORTED                                        0x2601
#define PARAMETER_VALUE_INVALID                                        0x2602
#define PARAMETERS_CHANGED                                             0x2A00
#define PARITY_DATA_MISMATCH                                           0x6902
#define PARTIAL_DEFECT_LIST_TRANSFER                                   0x1F00
#define PARTITION_OR_COLLECTION_CONTAINS_USER_OBJECTS                  0x2C0A
#define PERIPHERAL_DEVICE_WRITE_FAULT                                  0x0300
#define PERMANENT_WRITE_PROTECT                                        0x2705
#define PERSISTENT_PREVENT_CONFLICT                                    0x2C06
#define PERSISTENT_WRITE_PROTECT                                       0x2704
#define PHY_TEST_FUNCTION_IN_PROGRESS                                  0x4706
#define POSITION_ERROR_RELATED_TO_TIMING                               0x5002
#define POSITION_PAST_BEGINNING_OF_MEDIUM                              0x3B0C
#define POSITION_PAST_END_OF_MEDIUM                                    0x3B0B
#define POSITIONING_ERROR_DETECTED_BY_READ_OF_MEDIUM                   0x1502
#define POWER_CALIBRATION_AREA_ALMOST_FULL                             0x7301
#define POWER_CALIBRATION_AREA_ERROR                                   0x7303
#define POWER_CALIBRATION_AREA_IS_FULL                                 0x7302
#define POWER_ON_OCCURRED                                              0x2901
#define POWER_ON_RESET_OR_BUS_DEVICE_RESET_OCCURRED                    0x2900
#define POWER_STATE_CHANGE_TO_ACTIVE                                   0x5E41
#define POWER_STATE_CHANGE_TO_DEVICE_CONTROLM                          0x5E47
#define POWER_STATE_CHANGE_TO_IDLE                                     0x5E42
#define POWER_STATE_CHANGE_TO_SLEEP                                    0x5E45
#define POWER_STATE_CHANGE_TO_STANDBY                                  0x5E43
#define POWER_ON_OR_SELF_TEST_FAILURE_SHOULD_USE_40_NN                 0x4200
#define PREVIOUS_BUSY_STATUS                                           0x2C07
#define PREVIOUS_RESERVATION_CONFLICT_STATUS                           0x2C09
#define PREVIOUS_TASK_SET_FULL_STATUS                                  0x2C08
#define PRIMARY_DEFECT_LIST_NOT_FOUND                                  0x1C01
// part 11
#define PRIORITY_CHANGED                                               0x2A08
#define PROGRAM_MEMORY_AREA_IS_FULL                                    0x7305
#define PROGRAM_MEMORY_AREA_UPDATE_FAILURE                             0x7304
#define PROTOCOL_SERVICE_CRC_ERROR                                     0x4705
#define QUOTA_ERROR                                                    0x5507
#define RAM_FAILURE_SHOULD_USE_40_NN                                   0x4000
#define RANDOM POSITIONING ERROR                                       0x1500
#define READ_ERROR_FAILED_RETRANSMISSION_REQUEST                       0x1113
#define READ_ERROR_LOSS_OF_STREAMING                                   0x1111
#define READ_OF_SCRAMBLED_SECTOR_WITHOUT_AUTHENTICATION                0x6F03
#define READ_PAST_BEGINNING_OF_MEDIUM                                  0x3B0A
#define READ_PAST_END_OF_MEDIUM                                        0x3B09
#define READ_PAST_END_OF_USER_OBJECT                                   0x3B17
#define READ_RETRIES_EXHAUSTED                                         0x1101
#define REBUILD_FAILURE_OCCURRED                                       0x6C00
#define RECALCULATE_FAILURE_OCCURRED                                   0x6D00
#define RECORD_NOT_FOUND                                               0x1401
#define RECORD_NOT_FOUND_DATA_AUTO_REALLOCATED                         0x1406
#define RECORD_NOT_FOUND_RECOMMEND_REASSIGNMENT                        0x1405
#define RECORDED_ENTITY_NOT_FOUND                                      0x1400
#define RECOVERED_DATA_DATA_AUTO_REALLOCATED                           0x1802
#define RECOVERED_DATA_RECOMMEND_REASSIGNMENT                          0x1805
#define RECOVERED_DATA_RECOMMEND_REWRITE                               0x1806
#define RECOVERED_DATA_USING_PREVIOUS_SECTOR_ID                        0x1705
#define RECOVERED_DATA_WITH_CIRC                                       0x1803
#define RECOVERED_DATA_WITH_ECC_DATA_REWRITTEN                         0x1807
#define RECOVERED_DATA_WITH_ERROR_CORR_AND_RETRIES_APPLIED             0x1801
#define RECOVERED_DATA_WITH_ERROR_CORRECTION_APPLIED                   0x1800
#define RECOVERED_DATA_WITH_L_EC                                       0x1804
#define RECOVERED_DATA_WITH_LINKING                                    0x1808
#define RECOVERED_DATA_WITH_NEGATIVE_HEAD_OFFSET                       0x1703
#define RECOVERED_DATA_WITH_NO_ERROR_CORRECTION_APPLIED                0x1700
#define RECOVERED_DATA_WITH_POSITIVE_HEAD_OFFSET                       0x1702
#define RECOVERED_DATA_WITH_RETRIES                                    0x1701
#define RECOVERED_DATA_WITH_RETRIES_AND_OR_CIRC_APPLIED                0x1704
#define RECOVERED_DATA_WITHOUT_ECC_DATA_AUTO_REALLOCATED               0x1706
#define RECOVERED_DATA_WITHOUT_ECC_DATA_REWRITTEN                      0x1709
#define RECOVERED_DATA_WITHOUT_ECC_RECOMMEND_REASSIGNMENT              0x1707
#define RECOVERED_DATA_WITHOUT_ECC_RECOMMEND_REWRITE                   0x1708
// part 12
#define RECOVERED_ID_WITH_ECC_CORRECTION                               0x1E00
#define REDUNDANCY_GROUP_CREATED_OR_MODIFIED                           0x3F06
#define REDUNDANCY_GROUP_DELETED                                       0x3F07
#define REDUNDANCY_LEVEL_GOT_BETTER                                    0x6B01
#define REDUNDANCY_LEVEL_GOT_WORSE                                     0x6B02
#define REGISTRATIONS_PREEMPTED                                        0x2A05
#define REMOVE_OF_LOGICAL_UNIT_FAILED                                  0x6705
#define REPORTED_LUNS_DATA_HAS_CHANGED                                 0x3F0E
#define REPOSITION_ERROR                                               0x3B08
#define RESERVATIONS_PREEMPTED                                         0x2A03
#define RESERVATIONS_RELEASED                                          0x2A04
#define REWIND_OPERATION_IN_PROGRESS                                   0x001A
#define RIBBON_INK_OR_TONER_FAILURE                                    0x3600
#define RMA_PMA_IS_ALMOST_FULL                                         0x7306
#define ROUNDED_PARAMETER                                              0x3700
#define STATUS_CHANGE                                                  0x5C00
#define SAVING_PARAMETERS_NOT_SUPPORTED                                0x3900
#define SCAN_HEAD_POSITIONING_ERROR                                    0x6200
#define SCSI_BUS_RESET_OCCURRED                                        0x2902
#define SCSI_PARITY_ERROR                                              0x4700
#define SCSI_PARITY_ERROR_DETECTED_DURING_ST_DATA_PHASE                0x4702
#define SCSI_TO_HOST_SYSTEM_INTERFACE_FAILURE                          0x5400
#define SECURITY_AUDIT_VALUE_FROZEN                                    0x2404
#define SECURITY_WORKING_KEY_FROZEN                                    0x2405
#define SELECT_OR_RESELECT_FAILURE                                     0x4500
#define SEQUENTIAL_POSITIONING_ERROR                                   0x3B00
#define SERVO_IMPENDING_FAILURE_ACCESS_TIMES_TOO_HIGH                  0x5D45
#define SERVO_IMPENDING_FAILURE_CHANNEL_PARAMETRICS                    0x5D47
#define SERVO_IMPENDING_FAILURE_CONTROLLER_DETECTED                    0x5D48
#define SERVO_IMPENDING_FAILURE_DATA_ERROR_RATE_TOO_HIGH               0x5D42
#define SERVO_IMPENDING_FAILURE_DRIVE_CALIBRATION_RETRY_COUNT          0x5D4C
#define SERVO_IMPENDING_FAILURE_DRIVE_ERROR_RATE_TOO_HIGH              0x5D41
#define SERVO_IMPENDING_FAILURE_GENERAL_HARD_DRIVE_FAILURE             0x5D40
#define SERVO_IMPENDING_FAILURE_SEEK_ERROR_RATE_TOO_HIGH               0x5D43
#define SERVO_IMPENDING_FAILURE_SEEK_TIME_PERFORMANCE                  0x5D4A
#define SERVO_IMPENDING_FAILURE_SPIN_UP_RETRY_COUNT                    0x5D4B
#define SERVO_IMPENDING_FAILURE_START_UNIT_TIMES_TOO_HIGH              0x5D46
#define SERVO_IMPENDING_FAILURE_THROUGHPUT_PERFORMANCE                 0x5D49
#define SERVO_IMPENDING_FAILURE_TOO_MANY_BLOCK_REASSIGNS               0x5D44
// part 13
#define SESSION_FIXATION_ERROR                                         0x7200
#define SESSION_FIXATION_ERROR_INCOMPLETE_TRACK_IN_SESSION             0x7203
#define SESSION_FIXATION_ERROR_WRITING_LEAD_IN                         0x7201
#define SESSION_FIXATION_ERROR_WRITING_LEAD_OUT                        0x7202
#define SET_CAPACITY_OPERATION_IN_PROGRESS                             0x001B
#define SET_TARGET_PORT_GROUPS_COMMAND_FAILED                          0x670A
#define SETMARK_DETECTED                                               0x0003
#define SLEW_FAILURE                                                   0x3B04
#define SOME_COMMANDS_CLEARED_BY_ISCSI_PROTOCOL_EVENT                  0x477F
#define SPARE_AREA_EXHAUSTION_PREDICTION_THRESHOLD_EXCEEDED            0x5D03
#define SPARE_CREATED_OR_MODIFIED                                      0x3F08
#define SPARE_DELETED                                                  0x3F09
#define SPINDLE_IMPENDING_FAILURE_ACCESS_TIMES_TOO_HIGH                0x5D55
#define SPINDLE_IMPENDING_FAILURE_CHANNEL_PARAMETRICS                  0x5D57
#define SPINDLE_IMPENDING_FAILURE_CONTROLLER_DETECTED                  0x5D58
#define SPINDLE_IMPENDING_FAILURE_DATA_ERROR_RATE_TOO_HIGH             0x5D52
#define SPINDLE_IMPENDING_FAILURE_DRIVE_CALIBRATION_RETRY_COUNT        0x5D5C
#define SPINDLE_IMPENDING_FAILURE_DRIVE_ERROR_RATE_TOO_HIGH            0x5D51
#define SPINDLE_IMPENDING_FAILURE_GENERAL_HARD_DRIVE_FAILURE           0x5D50
#define SPINDLE_IMPENDING_FAILURE_SEEK_ERROR_RATE_TOO_HIGH             0x5D53
#define SPINDLE_IMPENDING_FAILURE_SEEK_TIME_PERFORMANCE                0x5D5A
#define SPINDLE_IMPENDING_FAILURE_SPIN_UP_RETRY_COUNT                  0x5D5B
#define SPINDLE_IMPENDING_FAILURE_START_UNIT_TIMES_TOO_HIGH            0x5D56
#define SPINDLE_IMPENDING_FAILURE_THROUGHPUT_PERFORMANCE               0x5D59
#define SPINDLE_IMPENDING_FAILURE_TOO_MANY_BLOCK_REASSIGNS             0x5D54
#define SPINDLE_SERVO_FAILURE                                          0x0903
#define SPINDLES_NOT_SYNCHRONIZED                                      0x5C02
#define SPINDLES_SYNCHRONIZED                                          0x5C01
#define STANDBY_CONDITION_ACTIVATED_BY_COMMAND                         0x5E04
#define STANDBY_CONDITION_ACTIVATED_BY_TIMER                           0x5E02
#define STATE_CHANGE_HAS_OCCURRED                                      0x6B00
#define SYNCHRONOUS_DATA_TRANSFER_ERROR                                0x1B00
#define SYSTEM_BUFFER_FULL                                             0x5501
#define SYSTEM_RESOURCE_FAILURE                                        0x5500
#define TAGGED_OVERLAPPED_COMMANDS_NN_EQUAL_TASK_TAG                   0x4D00
#define TAPE_LENGTH_ERROR                                              0x3300
#define TAPE_OR_ELECTRONIC_VERTICAL_FORMS_UNIT_NOT_READY               0x3B03
#define TAPE_POSITION_ERROR_AT_BEGINNING_OF_MEDIUM                     0x3B01
#define TAPE_POSITION_ERROR_AT_END_OF_MEDIUM                           0x3B02                             
// part 14
#define TARGET_OPERATING_CONDITIONS_HAVE_CHANGED                       0x3F00
#define THIRD_PARTY_DEVICE_FAILURE                                     0x0D01
#define THRESHOLD_CONDITION_MET                                        0x5B01
#define THRESHOLD_PARAMETERS_NOT_SUPPORTED                             0x2603
#define TIMEOUT_ON_LOGICAL_UNIT                                        0x3E02
#define TIMESTAMP_CHANGED                                              0x2A10
#define TOO_MANY_SEGMENT_DESCRIPTORS                                   0x2608
#define TOO_MANY_TARGET_DESCRIPTORS                                    0x2606
#define TOO_MANY_WINDOWS_SPECIFIED                                     0x2C01
#define TOO_MUCH_WRITE_DATA                                            0x4B02
#define TRACK_FOLLOWING_ERROR                                          0x0900
#define TRACKING_SERVO_FAILURE                                         0x0901
#define TRANSCEIVER_MODE_CHANGED_TO_LVD                                0x2906
#define TRANSCEIVER_MODE_CHANGED_TO_SINGLE_ENDED                       0x2905
#define UNABLE_TO_ACQUIRE_VIDEO                                        0x6101
#define UNABLE_TO_RECOVER_TABLE_OF_CONTENTS                            0x5700
#define UNEXPECTED_INEXACT_SEGMENT                                     0x260A
#define UNLOAD_TAPE_FAILURE                                            0x5301
#define UNREACHABLE_COPY_TARGET                                        0x0804
#define UNRECOVERED_READ_ERROR                                         0x1100
#define UNRECOVERED_READ_ERROR_AUTO_REALLOCATE_FAILED                  0x1104
#define UNRECOVERED_READ_ERROR_RECOMMEND_REASSIGNMENT                  0x110B
#define UNRECOVERED_READ_ERROR_RECOMMEND_REWRITE_THE_DATA              0x110C
#define UNSUCCESSFUL_SOFT_RESET                                        0x4600
#define UNSUPPORTED_ENCLOSURE_FUNCTION                                 0x3501
#define UNSUPPORTED_SEGMENT_DESCRIPTOR_TYPE_CODE                       0x2609
#define UNSUPPORTED_TARGET_DESCRIPTOR_TYPE_CODE                        0x2607
#define UPDATED_BLOCK_READ                                             0x5900
#define VERIFY_OPERATION_IN_PROGRESS                                   0x001C
#define VIDEO_ACQUISITION_ERROR                                        0x6100
#define VOLTAGE_FAULT                                                  0x6500
#define VOLUME_SET_CREATED_OR_MODIFIED                                 0x3F0A
#define VOLUME_SET_DEASSIGNED                                          0x3F0C
#define VOLUME_SET_DELETED                                             0x3F0B
#define VOLUME_SET_REASSIGNED                                          0x3F0D
#define WARNING                                                        0x0B00
#define WARNING_ENCLOSURE_DEGRADED                                     0x0B02
#define WARNING_SPECIFIED_TEMPERATURE_EXCEEDED                         0x0B01
#define WORM_MEDIUM_OVERWRITE_ATTEMPTED                                0x300C
// part 15
#define WRITE_APPEND_ERROR                                             0x5000
#define WRITE_APPEND_POSITION_ERROR                                    0x5001
#define WRITE_ERROR                                                    0x0C00
#define WRITE_ERROR_AUTO_REALLOCATION_FAILED                           0x0C02
#define WRITE_ERROR_LOSS_OF_STREAMING                                  0x0C09
#define WRITE_ERROR_NOT_ENOUGH_UNSOLICITED_DATA                        0x0C0D
#define WRITE_ERROR_PADDING_BLOCKS_ADDED                               0x0C0A
#define WRITE_ERROR_RECOMMEND_REASSIGNMENT                             0x0C03
#define WRITE_ERROR_RECOVERED_WITH_AUTO_REALLOCATION                   0x0C01
#define WRITE_ERROR_RECOVERY_FAILED                                    0x0C08
#define WRITE_ERROR_RECOVERY_NEEDED                                    0x0C07
#define WRITE_ERROR_UNEXPECTED_UNSOLICITED_DATA                        0x0C0C
#define WRITE_PROTECTED                                                0x2700
#define ZONED_FORMATTING_FAILED_DUE_TO_SPARE_LINKING                   0x3102

//----------------------------------------------------------------------------
struct s_scsi_sense_data                                               
{                                                                      
    uint8       valid;                                                 
    uint8       response_code;                                         
    uint8       filemark;                                              
    uint8       eom;                                             
    uint8       ili;
    uint8       sense_key;
    uint8       information[4];
    uint8       additional_sense_length;
    uint8       command_specific_information[4];
    uint8       additional_sense_code;
    uint8       additional_sense_code_qualifier;
    uint8       field_replaceable_unit_code;
    uint8       sksv;
    uint8       sense_key_specific[3];
};
//----------------------------------------------------------------------------
void scsi_mode_sense_10(void* BufferSCSICommand, int32 iLLBAA, int32 iDBD, int32 iPC, int32 iPAGE_CODE, int32 iSUBPAGE_CODE, int32 iALLOCATION_LENGTH, int32 iCONTROL);
void scsi_mode_sense_6(void* BufferSCSICommand, int32 iDBD, int32 iPC, int32 iPAGE_CODE, int32 iSUBPAGE_CODE, int32 iALLOCATION_LENGTH, int32 iCONTROL);
void scsi_task_management_functions(void* BufferSCSICommand,int32 iAllocationLength);
void scsi_write_10(void* BufferSCSICommand, int32 iLBA, int32 iTransferLength, int32 iWRPROTECT, int32 iDPO, int32 iFUA, int32 iFUA_NV, int32 iGROUP_NUMBER, int32 iCONTROL);
void scsi_read_10(void* BufferSCSICommand, int32 iLBA, int32 iTransferLength, int32 iRDPROTECT, int32 iDPO, int32 iFUA, int32 iFUA_NV, int32 iGROUP_NUMBER, int32 iCONTROL);
void scsi_write_and_verify_10(void* BufferSCSICommand, int32 iLBA, int32 iTransferLength, int32 iWRPROTECT, int32 iDPO, int32 iBYTCHK, int32 iGROUP_NUMBER, int32 iCONTROL);
void scsi_start_stot_unit(void* BufferSCSICommand,int32 iIMMED,int32 iPOWER_CONDITION, int32 iLOEJ, int32 iSTART,int32 iCONTROL);
void scsi_inquiry(void* BufferSCSICommand,int32 iEVPD, int32 iPAGECODE, int32 iALLOCATIONLENGTH,int32 iCONTROL);
void scsi_read_capacity(void* BufferSCSICommand,int32 iLBA,int32 iPMI,int32 iCONTROL);
void scsi_test_unit_ready(void* BufferSCSICommand);
void scsi_request_sense(void* BufferSCSICommand,int32 iDESC,int32 iALLOCATION_LENGTH,int32 iCONTROL);
void scsi_pre_fetch_10(void* BufferSCSICommand, int32 iLBA, int32 iPreFetchLength, int32 iGROUP_NUMBER, int32 iCONTROL);
#endif //__SCSI_Command_H__

